マウスオーバーで詳細表示
shugo/roomresrv pull request #19
Opened 2017-02-24 05:38 UTC by 723gt

2017-02-24 05:52 UTC, shugo requested changes
コメントしましたので修正をお願いします。

2017-02-24 05:52 UTC, shugo commented on app/assets/javascripts/calendar.coffee
> +            event.tooltip =  '<span id="tooltip"> ' + popup_msg + '</span>'
用途に「<script>alert("hello")</script>」とか入れるとクロスサイトスクリプティング脆弱性があるようですので、適宜エスケープを行ってください。

2017-02-24 05:52 UTC, shugo commented on app/assets/stylesheets/calendar.scss
> +        background:#335588;
もうちょっと余白があった方がいいかもしれません。

2017-02-27 00:16 UTC, TakuyaNoguchi commented on app/assets/javascripts/calendar.coffee
> +          console.log("hoge")
動作確認用のコードが残っているようです。

2017-02-27 01:32 UTC, shugo commented on app/assets/javascripts/calendar.coffee
> +            event.tooltip =  '<span id="tooltip"> ' + popup_msg + '</span>'
ちなみにcalendar.coffeeでhというエスケープ用の関数を用意しています。

2017-02-27 05:26 UTC, merged

2017-02-27 05:27 UTC, shugo commented
:+1: